import AppKit
import XCTest
@testable import ClipboardShelf

final class ClipboardServiceTests: XCTestCase {
    func testBinaryAndMultipleItemRepresentationsSurviveRestore() async throws {
        try await MainActor.run {
            let board = NSPasteboard(name: .init("ClipboardShelfTests.\(UUID().uuidString)"))
            defer { board.releaseGlobally() }
            let service = ClipboardService(pasteboard: board, sourceProvider: { ("Test Editor", "test.editor") })
            let binary = Data([0, 1, 255, 0, 128, 76, 0])
            let first = NSPasteboardItem()
            XCTAssertTrue(first.setData(binary, forType: .png))
            XCTAssertTrue(first.setString("图像说明", forType: .string))
            let second = NSPasteboardItem()
            XCTAssertTrue(second.setString("second item", forType: .string))
            XCTAssertTrue(second.setData(Data([4, 5, 6]), forType: .init("test.custom-format")))
            board.clearContents()
            XCTAssertTrue(board.writeObjects([first, second]))

            var records: [ClipRecord] = []
            service.onCapture = { records.append($0) }
            service.captureNow()
            let record = try XCTUnwrap(records.first)
            XCTAssertEqual(record.kind, .image)
            XCTAssertEqual(record.text, "图像说明\nsecond item")
            XCTAssertEqual(record.sourceApp, "Test Editor")
            XCTAssertEqual(record.items.count, 2)

            board.clearContents()
            try service.restore(record)
            let restored = try XCTUnwrap(board.pasteboardItems)
            XCTAssertEqual(restored.count, 2)
            XCTAssertEqual(restored[0].data(forType: .png), binary)
            XCTAssertEqual(restored[0].string(forType: .string), "图像说明")
            XCTAssertEqual(restored[1].string(forType: .string), "second item")
            XCTAssertEqual(restored[1].data(forType: .init("test.custom-format")), Data([4, 5, 6]))
            service.pollChanges()
            XCTAssertEqual(records.count, 1, "A restore must not be recaptured as a new copy.")
            service.clear()
            service.pollChanges()
            XCTAssertEqual(records.count, 1)
        }
    }

    func testPlainTextRestoreRemovesFormattingWithoutChangingHistory() async throws {
        try await MainActor.run {
            let board = NSPasteboard(name: .init("ClipboardShelfTests.\(UUID().uuidString)"))
            defer { board.releaseGlobally() }
            let service = ClipboardService(pasteboard: board)
            let record = ClipRecord(items: [ClipItem(representations: [
                NSPasteboard.PasteboardType.html.rawValue: Data("<b>Hello</b>".utf8),
                NSPasteboard.PasteboardType.string.rawValue: Data("Hello".utf8)
            ])], text: "Hello", kind: .richText)
            try service.restore(record, plainText: true)
            XCTAssertEqual(board.string(forType: .string), "Hello")
            XCTAssertNil(board.data(forType: .html))
            XCTAssertEqual(record.items[0].representations.count, 2)
        }
    }

    func testSecretAndTransientMarkersIgnoreEntireMultiItemClipboard() async {
        await MainActor.run {
            let board = NSPasteboard(name: .init("ClipboardShelfTests.\(UUID().uuidString)"))
            defer { board.releaseGlobally() }
            let service = ClipboardService(pasteboard: board, sourceProvider: { ("Editor", "test.editor") })
            var records: [ClipRecord] = []
            service.onCapture = { records.append($0) }
            for marker in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"] {
                let first = NSPasteboardItem()
                first.setString("must stay private", forType: .string)
                let second = NSPasteboardItem()
                second.setData(Data(), forType: .init(marker))
                board.clearContents()
                XCTAssertTrue(board.writeObjects([first, second]))
                service.captureNow()
            }
            XCTAssertTrue(records.isEmpty)
        }
    }

    func testPasswordManagerSourceIsIgnoredEvenWithoutMarker() async {
        await MainActor.run {
            let board = NSPasteboard(name: .init("ClipboardShelfTests.\(UUID().uuidString)"))
            defer { board.releaseGlobally() }
            let service = ClipboardService(pasteboard: board, sourceProvider: { ("1Password", "com.1password.1password") })
            var captures = 0
            service.onCapture = { _ in captures += 1 }
            board.clearContents()
            board.setString("private", forType: .string)
            service.captureNow()
            XCTAssertEqual(captures, 0)
        }
    }

    func testStartupAndPauseDoNotReadPastClipboardContents() async {
        await MainActor.run {
            let board = NSPasteboard(name: .init("ClipboardShelfTests.\(UUID().uuidString)"))
            defer { board.releaseGlobally() }
            let service = ClipboardService(pasteboard: board, sourceProvider: { ("Editor", "test.editor") })
            defer { service.stop() }
            var texts: [String?] = []
            service.onCapture = { texts.append($0.text) }
            board.clearContents()
            board.setString("before launch", forType: .string)
            service.start()
            service.pollChanges()
            XCTAssertTrue(texts.isEmpty)

            board.clearContents()
            board.setString("new copy", forType: .string)
            service.pollChanges()
            XCTAssertEqual(texts, ["new copy"])
            service.isPaused = true
            board.clearContents()
            board.setString("while paused", forType: .string)
            service.isPaused = false
            service.pollChanges()
            XCTAssertEqual(texts, ["new copy"])

            // Manual capture is an explicit request and works while monitoring is paused.
            service.isPaused = true
            service.captureNow()
            XCTAssertEqual(texts, ["new copy", "while paused"])
        }
    }

    func testOversizedCaptureIsRejectedWithoutPartialHistory() async {
        await MainActor.run {
            let board = NSPasteboard(name: .init("ClipboardShelfTests.\(UUID().uuidString)"))
            defer { board.releaseGlobally() }
            let service = ClipboardService(pasteboard: board, sourceProvider: { ("Editor", "test.editor") })
            var captures = 0
            var notices: [String] = []
            service.onCapture = { _ in captures += 1 }
            service.onNotice = { notices.append($0) }
            board.clearContents()
            board.setData(Data(repeating: 42, count: HistoryPolicy.maximumEntryBytes + 1), forType: .png)
            service.captureNow()
            XCTAssertEqual(captures, 0)
            XCTAssertTrue(notices.contains(where: { $0.contains("20 MB") }))
        }
    }

    func testFileURLIsPreservedWhileVolatileFilePromiseIsOmitted() async throws {
        try await MainActor.run {
            let board = NSPasteboard(name: .init("ClipboardShelfTests.\(UUID().uuidString)"))
            defer { board.releaseGlobally() }
            let service = ClipboardService(pasteboard: board, sourceProvider: { ("Finder", "com.apple.finder") })
            let fileURL = "file:///tmp/ClipboardShelf-test-only-no-file-access.txt"
            let item = NSPasteboardItem()
            item.setString(fileURL, forType: .fileURL)
            item.setData(Data("temporary-provider".utf8), forType: .init("com.apple.pasteboard.promised-file-url"))
            board.clearContents()
            XCTAssertTrue(board.writeObjects([item]))
            var captured: ClipRecord?
            service.onCapture = { captured = $0 }
            service.captureNow()
            let record = try XCTUnwrap(captured)
            XCTAssertEqual(record.kind, .files)
            XCTAssertEqual(record.items[0].representations.count, 1)
            try service.restore(record)
            XCTAssertEqual(board.string(forType: .fileURL), fileURL)
        }
    }

    func testHTMLPreviewCanBeDerivedWithoutAnHTMLRenderer() async throws {
        try await MainActor.run {
            let board = NSPasteboard(name: .init("ClipboardShelfTests.\(UUID().uuidString)"))
            defer { board.releaseGlobally() }
            let service = ClipboardService(pasteboard: board, sourceProvider: { ("Browser", "test.browser") })
            let html = "<style>invisible</style><p>Hello &amp; &#x4E16;&#30028;</p><script>hidden()</script>"
            board.clearContents()
            board.setData(Data(html.utf8), forType: .html)
            var captured: ClipRecord?
            service.onCapture = { captured = $0 }
            service.captureNow()
            let record = try XCTUnwrap(captured)
            XCTAssertEqual(record.kind, .richText)
            XCTAssertEqual(record.text, "Hello & 世界")
            XCTAssertEqual(record.items[0].representations[NSPasteboard.PasteboardType.html.rawValue], Data(html.utf8))
        }
    }

    func testInvalidPlainTextRestoreLeavesCurrentClipboardUntouched() async throws {
        try await MainActor.run {
            let board = NSPasteboard(name: .init("ClipboardShelfTests.\(UUID().uuidString)"))
            defer { board.releaseGlobally() }
            let service = ClipboardService(pasteboard: board)
            board.clearContents()
            board.setString("keep current clipboard", forType: .string)
            let image = ClipRecord(items: [ClipItem(representations: [NSPasteboard.PasteboardType.png.rawValue: Data([1, 2])])], kind: .image)
            XCTAssertThrowsError(try service.restore(image, plainText: true))
            XCTAssertEqual(board.string(forType: .string), "keep current clipboard")
        }
    }
}
