#!/bin/bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_ROOT="$PROJECT_ROOT/.build"
SWIFTPM_BUILD="$BUILD_ROOT/swiftpm"
MODULE_CACHE="$BUILD_ROOT/ModuleCache"
DIST_DIR="$PROJECT_ROOT/dist"
APP_NAME="拾光剪贴板"
APP_PATH="$DIST_DIR/$APP_NAME.app"
SWIFT="$(xcrun --find swift)"

mkdir -p "$MODULE_CACHE" "$DIST_DIR"
export CLANG_MODULE_CACHE_PATH="$MODULE_CACHE"
export SWIFTPM_MODULECACHE_OVERRIDE="$MODULE_CACHE"

BUILD_ARGS=(--package-path "$PROJECT_ROOT" --scratch-path "$SWIFTPM_BUILD" --configuration release --disable-sandbox -Xswiftc -module-cache-path -Xswiftc "$MODULE_CACHE")
"$SWIFT" build "${BUILD_ARGS[@]}"
BIN_DIR="$("$SWIFT" build "${BUILD_ARGS[@]}" --show-bin-path)"

STAGING_ROOT="$(mktemp -d "$DIST_DIR/.build-app.XXXXXX")"
trap 'rm -rf "$STAGING_ROOT"' EXIT
STAGED_APP="$STAGING_ROOT/$APP_NAME.app"
mkdir -p "$STAGED_APP/Contents/MacOS" "$STAGED_APP/Contents/Resources"
cp "$BIN_DIR/ClipboardShelf" "$STAGED_APP/Contents/MacOS/ClipboardShelf"
cp "$PROJECT_ROOT/Resources/Info.plist" "$STAGED_APP/Contents/Info.plist"

ICONSET="$BUILD_ROOT/ClipboardShelf.iconset"
mkdir -p "$ICONSET"
"$SWIFT" -module-cache-path "$MODULE_CACHE" "$PROJECT_ROOT/Resources/AppIcon.swift" "$ICONSET"
iconutil -c icns "$ICONSET" -o "$STAGED_APP/Contents/Resources/ClipboardShelf.icns"
plutil -lint "$STAGED_APP/Contents/Info.plist"
codesign --force --sign - "$STAGED_APP"
codesign --verify --strict "$STAGED_APP"

# This path contains only the application generated by this script.
if [[ -e "$APP_PATH" ]]; then
  rm -rf "$APP_PATH"
fi
mv "$STAGED_APP" "$APP_PATH"
printf '\n已构建：%s\n' "$APP_PATH"
printf '启动：open "%s"\n' "$APP_PATH"
